# Generated by Django 3.0.4 on 2020-03-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.FloatField(null=True)),
                ('date', models.DateField()),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Jar')),
            ],
        ),
    ]
