# Generated by Django 3.0.4 on 2020-03-28 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedJar',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='jar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Jar'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='orderedJar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.OrderedJar'),
        ),
    ]
